### ISSUE TITLE
Is this realy a MOD-Player for Flipper ?

### ISSUE THREAD

**Issue by m-holler** [DrZlo13/flipper-zero-music-tracker#1]
Please update your readme.md for more information about your project.
And please give us a small howto, we can convert mod´s for flipper.
Thank you, and have a nice day.

**Comment by rullinoiz** [comment]
it looks like it is a player, but only plays a predetermined file which is included in [zero_tracker.c](https://github.com/DrZlo13/flipper-zero-music-tracker/blob/master/zero_tracker.c) in the `Channel` variables. im sure that if you're determined enough you can change that out and replace it with your own decoded mod file

**Comment by DrZlo13** [comment]
It's not a mod player, it's just a mono speaker tracker inspired by [MONOTONE tracker](https://github.com/MobyGamer/MONOTONE).

**Comment by m-holler** [comment]
Thank you for this information. I figuerd out, that it plays .mon files. I found a few of them an the Githubpage you linked above. Please add a Filebrowers to open such tunes. Btw. Do you found a mod to mon converter ? Would be great.

**Comment by rullinoiz** [comment]
> Thank you for this information. I figuerd out, that it plays .mon files. I found a few of them an the Githubpage you linked above. Please add a Filebrowers to open such tunes. Btw. Do you found a mod to mon converter ? Would be great.

the problem is that MOD has a lot more information than what the pc speaker can actually use, like instruments, so i don't know if a converter like that would be good enough to keep enough of the sound quality to discern the notes

**Comment by mkondel** [comment]
It doesnt look like a player of any file format at the moment. The song is programmed and performed in C code. There is also a viewer module that, I am guessing, will follow what has been programmed.  Still guessing, but this repo may already be using the same binary values as MOD files.
